// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/facility_type.go

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/jeremykane/go-boilerplate/internal/entity"
	errorx "github.com/jeremykane/go-boilerplate/pkg/errorx"
)

// MockFacilityTypeService is a mock of FacilityTypeService interface.
type MockFacilityTypeService struct {
	ctrl     *gomock.Controller
	recorder *MockFacilityTypeServiceMockRecorder
}

// MockFacilityTypeServiceMockRecorder is the mock recorder for MockFacilityTypeService.
type MockFacilityTypeServiceMockRecorder struct {
	mock *MockFacilityTypeService
}

// NewMockFacilityTypeService creates a new mock instance.
func NewMockFacilityTypeService(ctrl *gomock.Controller) *MockFacilityTypeService {
	mock := &MockFacilityTypeService{ctrl: ctrl}
	mock.recorder = &MockFacilityTypeServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFacilityTypeService) EXPECT() *MockFacilityTypeServiceMockRecorder {
	return m.recorder
}

// GetAll mocks base method.
func (m *MockFacilityTypeService) GetAll(ctx context.Context) ([]entity.FacilityType, *errorx.CustomError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].([]entity.FacilityType)
	ret1, _ := ret[1].(*errorx.CustomError)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockFacilityTypeServiceMockRecorder) GetAll(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockFacilityTypeService)(nil).GetAll), ctx)
}
